language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libgsl0-dev libhdf5-dev
  - pip install -r requirements.txt

install:
# disabling pip until problems with ez_setup are sorted.
#  - "pip install ."
  - python setup.py install

script: nosetests 

env:
  global:
  # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
  # via the "travis encrypt" command using the project repo's public key
  - secure: "XRqUqbcFEmdl5dN7bvBeMRRdMtN1Sfcfqc0iLx8mH1xRRy8lQgaSmWG3zdaY5WSFbCGwoPuv2IXy7bPbwX5DKYsH0OkXLfkgo3yjw5X4341hQjMn0B7scr0lM8QU30YcSgqniFxEwMOytmQsQGSKwlz6tMKs2R758GCR7xJIyi4="

addons:
  coverity_scan:
    project:
      name: "jeromekelleher/msprime"
      description: "Coalescent simulator"
    notification_email: jk@well.ox.ac.uk
    build_command_prepend: "cd lib && make avl.o"
    build_command:   "cd lib && make"
    branch_pattern: coverity_scan
