language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libgsl0-dev

install:
# disabling pip until problems with ez_setup are sorted.
#  - "pip install ."
  - python setup.py install

script: nosetests 
