language: python
python:
  - "2.7"
  - "3.1"
  - "3.2"
  - "3.3"
  - "3.4"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libgsl0-dev

install:
  - "pip install ."

script: nosetests 
